sudo: required
language: java
jdk:
    - openjdk7
services:
    - docker
install: true
script:
    - docker run -d --name="atsd-api-test" -e axiname="$travisLogin" -e axipass="$travisPassword" -e timezone="Asia/Kathmandu" axibase/atsd:api_test
    - while ! curl 172.17.0.2:8088 >/dev/null 2>&1; do echo "waiting to start $name server ..."; sleep 3; done
    - mvn clean test -Dmaven.test.failure.ignore=false -DserverName="172.17.0.2" -Dlogin=$travisLogin -Dpassword=$travisPassword -DloggerLevel=info
