language: java
jdk:
    - openjdk7
sudo: required
install: true
services:
    - docker
before_install:
    - docker pull axibase/atsd:api_test
    - docker run -d -p 8088:8088 -p 8081:8081 --name="atsd-api-test" -e axiname="$login" -e axipass="$password" axibase/atsd:api_test
script:
    - mvn clean test -Dmaven.test.failure.ignore=false -DserverName=127.0.0.1 -Dlogin=$travisLogin -Dpassword=$travisPassword -DloggerLevel=info
