language: java
sudo: false
install: true
script:
    - mvn clean test -Dmaven.test.failure.ignore=false -Dlogin=$travisLogin -Dpassword=$travisPassword -DhttpPort=49088 -DtcpPort=49081 -DloggerLevel=info
jdk:
    - openjdk7
